---
__app_cisetup__:
  force_threaded_perls: '0'
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead
  - dev
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
matrix:
  allow_failures:
    - perl: blead
  include:
    - env: COVERAGE=1
      perl: '5.24'
    - env: COVERAGE=1
      perl: '5.26'
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
### __app_cisetup__
# ---
# force_threaded_perls: 0

### __app_cisetup__
